name: Check links in notebooks
on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install pytest-check-links
          pytest --links-ext ipynb --check-links
        working-directory: ./lessons
